### ISSUE TITLE
`psql` attempts to connect to nonexistent database

### ISSUE THREAD

**Issue by korydraughn** [bihealth/irods-docker#46]
## Bug

This was seen on the **dev** branch.

The following line assumes a database exists by the name of `$IRODS_ICAT_DBUSER`. If that database does not exist, an error will occur and the container will exit.

https://github.com/bihealth/irods-docker/blob/507048e99aadc81d2f59234c1e00846572dbad38/docker/docker-entrypoint.sh#L51-L52

The error output will look similar to the following:
```
catalog-1   | 2024-12-10 16:47:54.126 UTC [85] FATAL:  database "irods" does not exist               
provider-1  | psql: error: FATAL:  database "irods" does not exist                                   
provider-1  | Create iCAT database                                                                   
provider-1  | Password:                                                                              
provider-1  | createdb: error: database creation failed: ERROR:  permission denied to create database
catalog-1   | 2024-12-10 16:47:54.194 UTC [86] ERROR:  permission denied to create database          
```

To fix this, an existing database must be passed to `psql`. `template1` seems like a decent option _(see comments on this [stackoverflow answer](https://stackoverflow.com/a/17757560/5818611))_.

This situation can be reproduced by pointing the image to a new postgres database.

**Comment by mikkonie** [comment]
Good catch. I've never ran into this myself, probably because we always initialize the postgres container with `POSTGRES_DB` in our Docker Compose network?

**Comment by korydraughn** [comment]
I suspect your compose project is designed such that this isn't something anyone has to worry about. The good thing is that this is trivial to fix.

I think part of the reason for this happening is due to how I launched the postgres database. I used this:
```
# From docker-compose.yml

catalog:                                                                          
    build:                                                                        
        context: irods_catalog
    environment:
        - POSTGRES_PASSWORD=irods
    restart: always
```
```
# From irods_catalog/Dockerfile

FROM postgres:14                                                
                                                               
COPY init-user-db.sh /docker-entrypoint-initdb.d/init-user-db.sh
```
```
# From irods_catalog/init-user-db.sh

#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE "ICAT";
    CREATE USER irods WITH PASSWORD 'irods';
    GRANT ALL PRIVILEGES ON DATABASE "ICAT" to irods;
EOSQL                                                                                   
```
